apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sweeper.fullname" . }}
  labels:
    {{- include "sweeper.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.port }}"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
