---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: demo-system
spec:
  selector:
    app: sweeper
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sweeper
  namespace: demo-system
spec:
  selector:
    app: sweeper
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
    nodePort: 30081
---
